[package]
name = "transport"
version = "0.1.2"
edition = "2024"

[dependencies]
wit-bindgen = "0.47.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
base64 = "0.22.1"
futures = "0.3"

[lib]
crate-type = ["cdylib"]
