[package]
name = "session-store"
version = "0.1.4"
edition = "2024"

[dependencies]
wit-bindgen = "0.48.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
base64 = "0.22.1"

[lib]
crate-type = ["cdylib"]
