[package]
name = "todo-list-auth"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.46"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[workspace]
