name: Release WIT Keyvalue Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Keyvalue package version (e.g. 0.1.0 or 0.1.0-alpha.1)'
        required: true
        type: string

jobs:
  release:
    name: Release Keyvalue Package
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/reusable-release-wit.yml
    with:
      package-name: keyvalue
      version: ${{ inputs.version }}
      wit-dir: wit/keyvalue/wit
      wkg-package: wasmcp:keyvalue
      tag-prefix: keyvalue-v
    secrets: inherit
